### ISSUE TITLE
create outdir if it doesn't exist

### ISSUE THREAD

**Issue by arvkevi** [NCBI-Hackathons/STREAMclean#27]

**Comment by kbshimmyo** [comment]
workdir too, I think, could be created.

obviously magicblastdir cannot be created - but we could also validate that a a bin/[executable] exists in it.

**Comment by arvkevi** [comment]
[this commit](https://github.com/NCBI-Hackathons/STREAMclean/commit/caea4bd0226824733b276964cb7e0290fe5a1322) fixes
